// <auto-generated />
using System;
using CreditoCarteraAdmin_AbInBev.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreditoCarteraAdmin_AbInBev.Migrations
{
    [DbContext(typeof(CartedaDBContext))]
    [Migration("20200923162045_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CreditoCarteraAdmin_AbInBev.Models.CarteraAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int>("LlamadasHechas")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmsEnviados")
                        .HasColumnName("SmsEnviados")
                        .HasColumnType("int");

                    b.Property<string>("ValorCartera")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarteraAnalytics");
                });

            modelBuilder.Entity("CreditoCarteraAdmin_AbInBev.Models.CreditoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ClienteNuevo")
                        .HasColumnType("bit");

                    b.Property<int>("CreditoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("CreditoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEnvios")
                        .HasColumnType("int");

                    b.Property<bool>("StatusCreditoNuevo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CreditoNuevo");
                });

            modelBuilder.Entity("CreditoCarteraAdmin_AbInBev.Models.FrecuenciaNotificaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CadaHora")
                        .HasColumnType("int");

                    b.Property<int>("CadaMinuto")
                        .HasColumnType("int");

                    b.Property<int>("DiasPrevios")
                        .HasColumnType("int");

                    b.Property<string>("HoraEnvio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCampaña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEnvios")
                        .HasColumnType("int");

                    b.Property<int>("RondasEnviadas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FrecuenciaNotificaciones");
                });

            modelBuilder.Entity("CreditoCarteraAdmin_AbInBev.Models.LlamadaNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlobStorageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiasPrevios")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LlamadaNotificacion");
                });

            modelBuilder.Entity("CreditoCarteraAdmin_AbInBev.Models.MensajeNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiasPrevios")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MensajeNotificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
